import { MessageCircle, MessagesSquare, Search, Users } from "lucide-react";
import { SimpleHeader } from "../components/SimpleHeader";

const sections = [
  { name: "Meta", desc: "The SpigotMC project, news, and community.", forums: [["News & Announcements", "Official news and announcements from SpigotMC.", "145", "27K", "Spigot & BungeeCord 26.2"], ["Feedback & Suggestions", "Ideas and suggestions for SpigotMC services.", "3.1K", "36.8K", "Add dark mode please"], ["Wiki Discussion", "Discussions related to wiki pages.", "48", "1.4K", "BungeeCord"]] },
  { name: "Spigot", desc: "Discussion, support, and development for Spigot.", forums: [["Spigot Discussion", "General discussion about Spigot and its features.", "13K", "114K", "Why is there a rule against…"], ["Spigot Help", "Technical support for server owners and administrators.", "32.7K", "182K", "Issue with Chart Unfolding"], ["Spigot Plugin Help", "Information and support for plugins.", "54K", "292K", "Plugin that puts items in chest"], ["Spigot Plugin Development", "API, Java, and Bukkit/Spigot plugin development.", "95K", "789K", "Adding Patch to BuildTools"]] },
  { name: "Server Administration", desc: "Performance, systems, and hosting.", forums: [["Performance Tweaking", "Optimization for servers, proxies, and plugins.", "4.7K", "42K", "Spark Analysis"], ["Systems Administration", "Linux, Windows, macOS, networks, and databases.", "3.8K", "31K", "Dedicated server specs"], ["Hosting Advice", "Independent advice about hardware and providers.", "4.5K", "64K", "Server hosting benchmarks"]] }
];

export default function Forums() { return <main className="sub-page"><SimpleHeader active="forums"/><section className="sub-hero"><span className="section-kicker">COMMUNITY</span><h1>Forums</h1><p>Discussion, support and development across the SpigotMC community.</p><button><Search size={18}/> Search forums</button></section><div className="forum-shell">{sections.map(section => <section className="forum-section" key={section.name}><header><div><h2>{section.name}</h2><p>{section.desc}</p></div><span>{section.forums.length} sections</span></header><div className="forum-list">{section.forums.map(f => <article key={f[0]}><div className="forum-icon"><MessagesSquare size={22}/></div><div className="forum-main"><h3>{f[0]}</h3><p>{f[1]}</p></div><div className="forum-count"><span><MessageCircle size={13}/>{f[2]}</span><span><Users size={13}/>{f[3]}</span></div><div className="forum-latest"><small>LATEST POST</small><b>{f[4]}</b><span>today</span></div></article>)}</div></section>)}</div></main> }
