import { MessageCircle, MessagesSquare, Search, Users } from "lucide-react";
import { SimpleHeader } from "../components/SimpleHeader";

const sections=[
 {name:"Meta",desc:"Il progetto SpigotMC, le novità e la community.",forums:[["News & Announcements","Notizie e comunicazioni ufficiali da SpigotMC.","145","27K","Spigot & BungeeCord 26.2"],["Feedback & Suggestions","Idee e suggerimenti sui servizi SpigotMC.","3.1K","36.8K","Add dark mode please"],["Wiki Discussion","Discussioni collegate alle pagine della wiki.","48","1.4K","BungeeCord"]]},
 {name:"Spigot",desc:"Discussione, assistenza e sviluppo per Spigot.",forums:[["Spigot Discussion","Discussione generale su Spigot e le sue funzionalità.","13K","114K","Why is there a rule against…"],["Spigot Help","Supporto tecnico per server owner e amministratori.","32.7K","182K","Issue with Chart Unfolding"],["Spigot Plugin Help","Informazioni e assistenza sui plugin.","54K","292K","Plugin that puts items in chest"],["Spigot Plugin Development","API, Java e sviluppo di plugin Bukkit/Spigot.","95K","789K","Adding Patch to BuildTools"]]},
 {name:"Server Administration",desc:"Prestazioni, sistemi e hosting.",forums:[["Performance Tweaking","Ottimizzazione di server, proxy e plugin.","4.7K","42K","Spark Analysis"],["Systems Administration","Linux, Windows, macOS, reti e database.","3.8K","31K","Dedicated server specs"],["Hosting Advice","Consigli imparziali su hardware e provider.","4.5K","64K","Server hosting benchmarks"]]}
];

export default function Forums(){return <main className="sub-page"><SimpleHeader active="forums"/><section className="sub-hero"><span className="section-kicker">COMMUNITY FORUM</span><h1>Parla. Impara.<br/><em>Costruisci insieme.</em></h1><p>Le categorie reali di SpigotMC, riorganizzate per trovare subito il posto giusto.</p><button><Search size={18}/> Cerca nel forum</button></section><div className="forum-shell">{sections.map(section=><section className="forum-section" key={section.name}><header><div><h2>{section.name}</h2><p>{section.desc}</p></div><span>{section.forums.length} sezioni</span></header><div className="forum-list">{section.forums.map(f=><article key={f[0]}><div className="forum-icon"><MessagesSquare size={22}/></div><div className="forum-main"><h3>{f[0]}</h3><p>{f[1]}</p></div><div className="forum-count"><span><MessageCircle size={13}/>{f[2]}</span><span><Users size={13}/>{f[3]}</span></div><div className="forum-latest"><small>ULTIMO MESSAGGIO</small><b>{f[4]}</b><span>oggi</span></div></article>)}</div></section>)}</div></main>}
