import { ArrowDownToLine, ExternalLink, Search, Star } from "lucide-react";
import { SimpleHeader } from "../components/SimpleHeader";

const plugins = [
  { name:"LuckPerms", version:"5.5.0", category:"Universal", description:"A fast and flexible permissions plugin for Bukkit, Spigot and BungeeCord.", author:"Luck", downloads:"8.6M", rating:"4.7", image:"/plugins/luckperms.png", href:"https://www.spigotmc.org/resources/luckperms.28140/" },
  { name:"ViaVersion", version:"5.11.0", category:"Tools and Utilities", description:"Allow newer Minecraft clients to connect to older server versions.", author:"ViaVersion", downloads:"5M+", rating:"4.8", image:"/plugins/viaversion.png", href:"https://www.spigotmc.org/resources/viaversion.19254/" },
  { name:"EssentialsX", version:"2.x", category:"Bukkit", description:"The essential plugin suite with commands and features for servers of every scale.", author:"EssentialsX", downloads:"2M+", rating:"4.8", image:"/plugins/essentialsx.png", href:"https://www.spigotmc.org/resources/essentialsx.9089/" },
  { name:"Vault", version:"1.7.3", category:"Economy", description:"A permissions, chat and economy API used throughout the Bukkit ecosystem.", author:"MilkBowl", downloads:"3M+", rating:"4.6", image:"/plugins/vault.png", href:"https://www.spigotmc.org/resources/vault.34315/" },
];

export default function Resources(){return <main className="sub-page"><SimpleHeader active="resources"/><section className="resource-hero"><div><span className="section-kicker">RESOURCE MANAGER</span><h1>Resources</h1><p>Popular real plugins published for the SpigotMC ecosystem.</p></div><label><Search size={20}/><input placeholder="Search resources…"/></label></section><section className="famous-resources"><header><div><h2>Popular plugins</h2><p>Recognisable projects used by Minecraft server owners.</p></div><a href="https://www.spigotmc.org/resources/">Open Resource Manager <ExternalLink/></a></header><div className="famous-plugin-list">{plugins.map(plugin=><a href={plugin.href} key={plugin.name}><img src={plugin.image} alt={`${plugin.name} logo`}/><div><span>{plugin.category}</span><h3>{plugin.name}<small>{plugin.version}</small></h3><p>{plugin.description}</p><em>by <b>{plugin.author}</b></em></div><aside><span><Star/>{plugin.rating}</span><span><ArrowDownToLine/>{plugin.downloads}</span><ExternalLink/></aside></a>)}</div></section></main>}
